name: Release

permissions:
  contents: write
  id-token: write

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type (leave empty for auto)'
        required: false
        type: choice
        options:
          - patch
          - minor
          - major
          - ''
        default: ''

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: JxJuly/github-actions/setup-environment@v0.0.4

      - name: Build
        run: pnpm run build

      - name: Release
        uses: JxJuly/github-actions/release-it@v0.0.5
        with:
          version_bump: ${{ github.event.inputs.version_bump }}
          github_token: ${{ secrets.GITHUB_TOKEN }}